version: '3.4'

services:
  gstore-api:
    image: antdimot/gstore
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
      TZ: Europe/Rome
    ports:
    - "5000:5000"
    links: 
    - gstore-db
    depends_on:
    - gstore-db
    volumes:
    - gstore-vol-api:/app
    networks:
    - backend
    - frontend
  gstore-db:
    image: mongo:4.0
    restart: always
    volumes:
    - gstore-vol-db:/data/db
    - gstore-vol-db:/data/configdb
    - gstore-vol-api:/docker-entrypoint-initdb.d/data.js
    networks:
    - backend
volumes:
  gstore-vol-db:
  gstore-vol-api:
networks:
  frontend:
  backend: