version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: GStore.API/Dockerfile
    image: antdimot/gstore
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Staging
      TZ: Europe/Rome
    ports:
    - 5000:5000
    links: 
    - db:gstore-db
    depends_on:
    - db
    volumes:
    - gstore-vol-api:/app
    networks:
      - backend
      - frontend
    container_name: gstore-api
  db:
    image: mongo:4.0
    restart: always
    environment:
      TZ: Europe/Rome
    volumes:
    - gstore-vol-db:/data/db
    - gstore-vol-db:/data/configdb
    - gstore-vol-api:/docker-entrypoint-initdb.d/data.js
    networks:
    - backend
    container_name: gstore-db
volumes:
  gstore-vol-db:
  gstore-vol-api:
networks:
  frontend:
  backend: