version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: GStore.API/Dockerfile
    image: antdimot/gstore
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Staging
      TZ: Europe/Rome
    ports:
    - 5000:5000
    links: 
    - db:gstore-db
    depends_on:
    - db
    volumes:
    - gstore:/srv/gstore
    networks:
      - backend
      - frontend
    container_name: gstore-api
  db:
    image: mongo:4.0
    restart: always
    environment:
      TZ: Europe/Rome
    volumes:
    - gstore:/data/db
    - gstore:/data/configdb
    - ../db:/docker-entrypoint-initdb.d/*.js
    networks:
    - backend
    container_name: gstore-db
volumes:
  gstore:
networks:
  frontend:
  backend: