version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: GStore.API/Dockerfile
    image: gstore/api
    environment:
    - ASPNETCORE_URLS=http://+:5000
    - ASPNETCORE_ENVIRONMENT=Staging
    ports:
    - 5000:5000
    links: 
    - db:gstore-db
    depends_on:
    - db
    volumes:
    - data:/srv/gstore
    container_name: gstore-api
  db:
    image: mongo:3.6.5
    ports:
    - 27017:27017 
    restart: always
    # environment:
    volumes:
    - data:/data/db
    container_name: gstore-db
volumes:
  data:
    name: gstore-vol01